import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import Navbar from "./components/Navbar";
import Link from "next/link";

import { verifySession } from "./lib/dal"; 

import { AppProvider } from "./context/provider";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let session = await verifySession()
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppProvider>
          {session.session && <Navbar />}
          {children}
          <Link href="/dashboard">Dashboard 1</Link>
          <Link href="/dashboard2">Dashboard 2</Link>
          <Link href="/dashboard3?id=35&name=dhruv">Dashboard 3</Link>
        </AppProvider>

      </body>
    </html>
  );
}
